# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('user_view', 'User View'), ('new_message', 'New Message'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_rejected', 'Friend Request Rejected'), ('became_friends', 'Became Friends'), ('new_post', 'New Post'), ('like', 'Like'), ('comment', 'Comment'), ('new_group_chat', 'New Group Chat'), ('default', 'Default')], default='default', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
