# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotice',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notices_use_recipie_ac1fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['recipient', '-created_at'], name='notices_use_recipie_4f192d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['is_read'], name='notices_use_is_read_de857a_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['notice_type'], name='notices_use_notice__6c52d1_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['recipient', 'notice_type'], name='notices_use_recipie_6e93a1_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['sender'], name='notices_use_sender__824d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['recipient', 'sender'], name='notices_use_recipie_4ac85d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['content_type', 'object_id'], name='notices_use_content_016b43_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotice',
            index=models.Index(fields=['-created_at'], name='notices_use_created_051106_idx'),
        ),
    ]
