# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='audio_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofilelike',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='audio_files.audiofile'),
        ),
        migrations.AddField(
            model_name='audiofilelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_hash'], name='audio_files_file_ha_cfe338_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['uploaded_at'], name='audio_files_uploade_6eba11_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['uploaded_by'], name='audio_files_uploade_96e4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofilelike',
            index=models.Index(fields=['audio', 'user'], name='audio_files_audio_i_88b8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofilelike',
            index=models.Index(fields=['user', 'audio'], name='audio_files_user_id_af8a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofilelike',
            index=models.Index(fields=['created_at'], name='audio_files_created_62abb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audiofilelike',
            unique_together={('user', 'audio')},
        ),
    ]
