# Generated by Django 5.1.4 on 2025-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Smart Social Network', max_length=100)),
                ('description', models.TextField(default='Smart Social Network is a modern and convenient social network created for comfortable communication.')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=11)),
                ('telegram_bot_token', models.CharField(default='', max_length=100)),
                ('telegram_bot_url', models.URLField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
