# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(db_index=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessagestatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chats.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatstatus',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='chats.chat'),
        ),
        migrations.AddField(
            model_name='chatstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-updated_at'], name='chats_chat_updated_c643eb_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['is_group', '-updated_at'], name='chats_chat_is_grou_18523f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'timestamp'], name='chats_chatm_chat_id_8fe442_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'is_read', 'timestamp'], name='chats_chatm_chat_id_d3edf4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'is_deleted', 'timestamp'], name='chats_chatm_chat_id_227da8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'is_deleted', 'is_read', 'timestamp'], name='chats_chatm_chat_id_3e0c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'is_read'], name='chats_chatm_sender__afe330_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagestatus',
            index=models.Index(fields=['user', 'is_deleted_for_me'], name='chats_chatm_user_id_691af3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessagestatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatstatus',
            index=models.Index(fields=['user', 'is_archived'], name='chats_chats_user_id_0f7bbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatstatus',
            unique_together={('chat', 'user')},
        ),
    ]
