# Generated by Django 5.1.4 on 2025-09-03 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]*$', message='Username can only contain lowercase letters and numbers...')], verbose_name='username'),
        ),
    ]
