# Generated by Django 5.1.4 on 2025-08-31 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecommentlike',
            index=models.Index(fields=['comment', 'user'], name='articles_ar_comment_9d2a69_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecommentlike',
            index=models.Index(fields=['user', 'comment'], name='articles_ar_user_id_a57fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecommentlike',
            index=models.Index(fields=['created_at'], name='articles_ar_created_566fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelike',
            index=models.Index(fields=['article', 'user'], name='articles_ar_article_a217f4_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelike',
            index=models.Index(fields=['user', 'article'], name='articles_ar_user_id_024a82_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelike',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b8c986_idx'),
        ),
    ]
