# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smart_password_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpassword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['user', 'created_at'], name='smart_passw_user_id_4dadb3_idx'),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['public_key'], name='smart_passw_public__129289_idx'),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['login'], name='smart_passw_login_9cfeb5_idx'),
        ),
    ]
