# Generated by Django 5.1.4 on 2025-08-31 05:21

import apps.user_images.utils.image
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(upload_to=apps.user_images.utils.image.user_image_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User image',
                'verbose_name_plural': 'User images',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='UserImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User image comment',
                'verbose_name_plural': 'User image comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImageCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User image comment like',
                'verbose_name_plural': 'User image comment likes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User image like',
                'verbose_name_plural': 'User image likes',
                'ordering': ('-created_at',),
            },
        ),
    ]
