# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimagecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimagecomment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_images.userimage'),
        ),
        migrations.AddField(
            model_name='userimagecommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_images.userimagecomment'),
        ),
        migrations.AddField(
            model_name='userimagecommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimagelike',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='user_images.userimage'),
        ),
        migrations.AddField(
            model_name='userimagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['uploaded_by', 'is_visible'], name='user_images_uploade_72538d_idx'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['is_visible'], name='user_images_is_visi_eda8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['uploaded_at'], name='user_images_uploade_ca9312_idx'),
        ),
        migrations.AddIndex(
            model_name='userimagecomment',
            index=models.Index(fields=['image', 'created_at'], name='user_images_image_i_e9d871_idx'),
        ),
        migrations.AddIndex(
            model_name='userimagecomment',
            index=models.Index(fields=['author'], name='user_images_author__84c04b_idx'),
        ),
        migrations.AddIndex(
            model_name='userimagecomment',
            index=models.Index(fields=['is_read'], name='user_images_is_read_deb4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='userimagecommentlike',
            index=models.Index(fields=['comment', 'user'], name='user_images_comment_da605b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userimagecommentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='userimagelike',
            index=models.Index(fields=['image', 'user'], name='user_images_image_i_64902b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userimagelike',
            unique_together={('user', 'image')},
        ),
    ]
