# Generated by Django 5.1.4 on 2025-08-31 05:21

import apps.user_files.utils.paths.doc
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.user_files.utils.paths.doc.user_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
