# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['uploaded_by', 'is_visible'], name='user_files__uploade_dbe480_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['is_visible'], name='user_files__is_visi_f98507_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['uploaded_at'], name='user_files__uploade_5f7692_idx'),
        ),
    ]
