# Generated by Django 5.1.4 on 2025-08-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('fake_news', 'Fake news'), ('misinformation', 'Misinformation'), ('scam', 'Scam'), ('phishing', 'Phishing'), ('hate_speech', 'Hate speech'), ('extremism', 'Extremism'), ('terrorism', 'Terrorism'), ('violence', 'Violence'), ('self_harm', 'Self-harm promotion'), ('harassment', 'Harassment'), ('bullying', 'Bullying'), ('threats', 'Threats'), ('blackmail', 'Blackmail'), ('nudity', 'Nudity'), ('pornography', 'Pornography'), ('sexual_content', 'Sexual content'), ('underage', 'Underage content'), ('doxing', 'Doxing'), ('private_info', 'Private information leak'), ('impersonation', 'Impersonation'), ('fake_account', 'Fake account'), ('copyright', 'Copyright infringement'), ('trademark', 'Trademark violation'), ('counterfeit', 'Counterfeit goods'), ('illegal_goods', 'Illegal goods'), ('drugs', 'Drugs'), ('weapons', 'Weapons'), ('animal_abuse', 'Animal abuse'), ('other', 'Other violation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Report submitted'), ('in_progress', 'Under review'), ('resolved', 'Report approved'), ('rejected', 'Report rejected'), ('closed', 'Report closed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
