# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendshiphistory',
            name='friendship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='friends.friendship'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['sender', 'receiver', 'status'], name='friends_fri_sender__994e91_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['receiver', 'sender', 'status'], name='friends_fri_receive_2f0272_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status'], name='friends_fri_status_8a71e9_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['created_at'], name='friends_fri_created_352191_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['updated_at'], name='friends_fri_updated_dd235c_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['sender', 'status'], name='friends_fri_sender__5307d9_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['receiver', 'status'], name='friends_fri_receive_dfe84a_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='no_self_friendship'),
        ),
        migrations.AddIndex(
            model_name='friendshiphistory',
            index=models.Index(fields=['friendship'], name='friends_fri_friends_d1cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='friendshiphistory',
            index=models.Index(fields=['changed_at'], name='friends_fri_changed_387ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='friendshiphistory',
            index=models.Index(fields=['new_status'], name='friends_fri_new_sta_4a6593_idx'),
        ),
    ]
