# Generated by Django 5.1.4 on 2025-08-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_visible_to_visitor', models.BooleanField(default=True)),
                ('is_visible_to_visited_user', models.BooleanField(default=True)),
                ('visited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['visited_user', 'visitor', '-timestamp'], name='visits_prof_visited_26f609_idx'), models.Index(fields=['visited_user', 'is_visible_to_visited_user', '-timestamp'], name='visits_prof_visited_6a8a5a_idx'), models.Index(fields=['visitor', 'is_visible_to_visitor', '-timestamp'], name='visits_prof_visitor_1498bd_idx'), models.Index(fields=['visited_user', 'is_read'], name='visits_prof_visited_6a7eaa_idx')],
                'unique_together': {('visitor', 'visited_user')},
            },
        ),
    ]
